name: metadata_fetch
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 0.4.1
homepage: https://github.com/jg-l/metadata_fetch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.6
  string_validator: ^1.0.0
  html: ^0.15.3

dev_dependencies:
  test: ^1.17.5
